version: '3.1'

services:
  rabbitmq:
    image: docker.io/bitnami/rabbitmq:latest
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '25672:25672'
      - '15672:15672'
    env_file: 
      - "./.env"
    environment:
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
    volumes:
       - rabbitmq-data:/bitnami
    healthcheck:
         test: rabbitmq-diagnostics -q ping
         interval: 30s
         timeout: 30s
         retries: 10
    networks:
      - frontend
  postgresql:
    image: postgres
    restart: always
    networks:
      - frontend
    ports:
      - 5432:5432
    env_file: 
      - "./.env"
    environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: twitch
    # environment:
    #     POSTGRES_DB: twitch
    #     POSTGRES_USER: postgres
    #     POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data


networks:
    frontend:
        driver: bridge

volumes:
  rabbitmq-data:
    driver: local