FROM python:3.10.7-buster

RUN mkdir /app
WORKDIR /app
COPY requirements-consumer.txt /app/requirements.txt
COPY .env /app/.env
COPY generate_pickle.py launch.sh consumer.py /app

RUN pip install -r requirements.txt
CMD ["bash", "launch.sh"]